[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[rpc_endpoints]
bsc = "${RPC_URL}"
bsc_testnet = "https://data-seed-prebsc-1-s1.binance.org:8545/"
bsc_mainnet = "https://bsc-dataseed.binance.org/"

[etherscan]
bsc = { key = "${ETHERSCAN_API_KEY}", url = "https://api.bscscan.com/api" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config